### ISSUE TITLE
if used with php, why not set launch=true?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/httpd-cnb#2]
**ANSWER:** I needed `php-cnb`, `httpd-cnb`, AND `php-web-cnb` to run a PHP app.

I apologise if this is a silly question - I'm desperately trying to figure out how to combine php/httpd buildpacks to run a php app.

https://github.com/cloudfoundry/httpd-cnb/blob/master/cmd/detect/main.go#L53-L56 says that if `php-cnb` is also in th plan then "yay, let's use php" - but then it returns `buildplan.BuildPlan{}` and not the later buildplan:

```
buildplan.BuildPlan{
		httpd.Dependency: buildplan.Dependency{
			Version:  buildpackYAML.Config.Version,
			Metadata: buildplan.Metadata{"launch": true},
```

The output I get (plus my own buildpack) is:

```
[detector] Trying group of 3...
[detector] ======== Output: Apache HTTP Server Buildpack ========
[detector]        PHP is in the buildplan, so preparing to serve PHP.
[detector] ======== Results ========
[detector] CF Pancake Buildpack: pass
[detector] PHP Buildpack: pass
[detector] Apache HTTP Server Buildpack: pass
===> RESTORING
[restorer] cache image 'pack-cache-37b5d697e610' not found, nothing to restore
===> ANALYZING
[analyzer] WARNING: image 'index.docker.io/library/8id6wrk0chqexwsg:latest' not found or requires authentication to access
[analyzer] WARNING: image 'index.docker.io/library/8id6wrk0chqexwsg:latest' has incompatible 'io.buildpacks.lifecycle.metadata' label
===> BUILDING
[builder] -----> CF Pancake Buildpack 0.3.0
[builder] -----> Pancake 0.2.3: Contributing to layer
[builder]        Downloading from https://github.com/cloudfoundry-community/cf-pancake/releases/download/v0.2.3/cf-pancake-linux-amd64.tar.xz
[builder]        Verifying checksum
[builder]        Installing to /layers/com.starkandwayne.cf-pancake/cf-pancake
[builder]
[builder] -----> PHP Buildpack 0.0.2
[builder]        Dependency version not specified, but is required
[builder]
[builder] -----> Apache HTTP Server Buildpack 0.0.2
[builder]
```
And my pancake integration tests exit with error `failed to launch: determine start command: process type web was not found`.

But when I change my integration tests to just `[pancake-cnb, httpd-cnb]` on a valid httpd-only app, it works.

Should https://github.com/cloudfoundry/httpd-cnb/blob/master/cmd/detect/main.go#L53-L56 be changed to look more like the BuildPlan at the end of the method?

**Comment by dmikusa-pivotal** [comment]
>I apologise if this is a silly question - I'm desperately trying to figure out how to combine php/httpd buildpacks to run a php app.

This is still in flux and a lot of these cnb's are still changing (and all need to be better documented), but hopefully, this graphic will explain a bit for now. It's pretty much up-to-date.

![PHP v3 Buildpacks](https://user-images.githubusercontent.com/4643262/58477360-4ef39180-8121-11e9-8b20-03e3fd65c425.png)

Biggest note is that I don't believe we have an Nginx buildpack at this time. The idea is it would function like HTTPD and be interchangeable.

**Comment by dmikusa-pivotal** [comment]
Here's an integration test that weaves them together -> https://github.com/cloudfoundry/php-web-cnb/blob/master/integration/deploy_a_php_app_with_all_modules_test.go#L118

**Comment by drnic** [comment]
Is there an implementation reason for splitting `php-cnb` and `php-web-cnb` into two CNBs; or is it exploratory/idealistic to breaking functionality into as many small CNBs as passible?

Could `php-cnb` have also implemented the optional behavior of `php-web-cnb`? Or can buildpacks only be "supply" (php-cnb) or have runtime features? (php-web-cnb)?

**Comment by dmikusa-pivotal** [comment]
>Is there an implementation reason for splitting php-cnb and php-web-cnb into two CNBs; or is it exploratory/idealistic to breaking functionality into as many small CNBs as passible?

My understanding is that the idea is to split things up so that they can be more composable. Having a buildpack that just delivers PHP, makes it composable in that you can substitute what provides PHP easily (changing compositions is as easy as creating a builder, `pack create-builder`). Want to use HHVM? Just add a CNB that supplies it and it should work well with the rest of the buildpack. Similarly, you could decide to use a PHP buildpack that provides binaries from some other source like Ubuntu's official package repo, or something like that. As long as PHP's there, it should work with the other buildpacks. The web servers are broken out in a similar way, so that it's easy to pick the one you want.

That's in theory at least. Right now I'm sure there are some little things you'd have to work out to get the contract just right and that's not documented/could change. Over time I hope it will solidify though and you can compose your own PHP stack by combining the different CNBs.

>Could php-cnb have also implemented the optional behavior of php-web-cnb? Or can buildpacks only be "supply" (php-cnb) or have runtime features? (php-web-cnb)?

I think you could have put everything into one buildpack like with v2. There's nothing to restrict that. It's just going to be a more complicated buildpack. Splitting them out makes them simpler and more focused and easier to test. Plus the benefits I mentioned about being able to compose them.

Once you start splitting things out, the order of how you run them becomes very important to get right. PHP has to come first because things like Composer need it to be there to run. At the same time, you don't know what version of PHP to install until you look at your Composer files to see what the user wants. If you want Composer in its own CNB, then that gets tricky. There are similar issues with the web server CNBs. Making a php-web CNB allowed us to defer a lot of the logic for what to install and how to configure it to the end of the detect & build cycles. That allowed us to have all the information to make decisions but also split out into multiple CNBs.

**Comment by drnic** [comment]
Thanks for explaining that.
